### ISSUE TITLE
Select where the style sheet goes

### ISSUE THREAD

**Issue by cmcaine** [fuzetsu/zaftig#4]
Useful for shadow dom or iframes.

Off topic: is generation of inline styles just for file size or are there other performance benefits?

**Comment by fuzetsu** [comment]
Fixed in 540919335c3f3872826ca55935e3876726d1b9b2 (among other things) :tada: 

```js
const style = document.createElement()
const newZ = z.new({ style })
```

> Off topic: is generation of inline styles just for file size or are there other performance benefits?

Do you mean attaching the styles directly to each element and generating a class for each?

If you style directly on each element zaftig basically ends up generating very simple flat css with very few nesting rules, which could potentially be faster for the browser process.
